### ISSUE TITLE
Create new acrhitecture using CNNs instead of FFNNs

### ISSUE THREAD

**Issue by sandorfoldi** [sandorfoldi/deeponet#19]

**Comment by SigurdThorlund** [comment]
"both NNs are general architectures, e.g., the branch NN can be replaced with a CNN or a ResNet."
        - https://www.sciencedirect.com/science/article/abs/pii/S0045782522001207 

        Idea is simply to reshape the input of the branch net to be a 2D image and use that
        for predictions.
